version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-elginbrian-com
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: edutech
      JWT_SECRET: secret
      JWT_EXPIRATION: 3600s
    ports:
      - '3003:3000'
    depends_on:
      - db
    networks:
      - elginbrian-network

  db:
    image: postgres:latest
    container_name: db-elginbrian-com
    environment:
      POSTGRES_DB: elginbrian
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - elginbrian-network

networks:
  elginbrian-network:
    driver: bridge
